/*let promise = new Promise((resolve, reject) => {
    let a = 1 + 1;
    //let a = 1 + 2;
    // if true resolve this promise
    if (a == 2){
        resolve('This is a Javascript\'s SUCCESSFUL PROMISE!!!');   
    }
    // else reject this promise
    else{
        reject("This is a FAILED PROMISE!!!");
    }
}); 

//console.log(promise);

promise.then((message) =>{
    console.log("This is inside of the .then method " + "'" + message + "'");
}).catch((message)=>{
    console.log("This is inside of the .catch method " + "'" + message + "'");
});*/

